name: Terraform CD

on:
  workflow_run:
    workflows: ["Terraform CI"]
    types:
      - completed

jobs:
  terraform-cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./envs/dev

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.0

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        id: apply
        env:
          TF_VAR_env: ${{ secrets.ENV }}
          TF_VAR_vpc_cidr: ${{ secrets.VPC_CIDR }}
          TF_VAR_public_subnet_cidr: ${{ secrets.PUBLIC_SUBNET_CIDR }}
          TF_VAR_az: ${{ secrets.AZ }}
          TF_VAR_owner: ${{ secrets.OWNER }}
        run: terraform apply -auto-approve -input=false
